<?php

declare(strict_types=1);

/**
 * Tüm droplist değerleri tek yerde. Anahtarlar İngilizce ASCII (DB), etiketler Türkçe (UI).
 */
return [
    'building_types' => ['apartman' => 'Apartman', 'site' => 'Site', 'rezidans' => 'Rezidans', 'ishani' => 'İş hanı / plaza', 'karma' => 'Karma kullanım'],
    'unit_types' => ['daire' => 'Daire', 'dukkan' => 'Dükkan', 'ofis' => 'Ofis', 'depo' => 'Depo', 'otopark' => 'Otopark', 'diger' => 'Diğer'],
    'unit_statuses' => ['dolu' => 'Dolu', 'bos' => 'Boş', 'tadilatta' => 'Tadilatta', 'pasif' => 'Pasif'],
    'person_types' => ['gercek' => 'Gerçek kişi', 'tuzel' => 'Tüzel kişi'],
    'occupancy_roles' => ['malik' => 'Malik', 'kiraci' => 'Kiracı', 'oturan' => 'Oturan (aile üyesi)', 'vekil' => 'Vekil'],
    'liability_modes' => ['malik' => 'Malik öder', 'kiraci' => 'Kiracı öder', 'paylasimli' => 'Paylaşımlı'],
    'charge_types' => [
        'aidat' => 'Aidat',
        'yakit' => 'Yakıt / ısınma',
        'demirbas' => 'Demirbaş',
        'ozel_gider' => 'Özel gider (ek ödeme)',
        'sayac' => 'Sayaç tüketimi',
        'gecikme' => 'Gecikme tazminatı',
        'devir' => 'Devir bakiyesi',
        'diger' => 'Diğer',
    ],
    'charge_statuses' => ['odenmedi' => 'Ödenmedi', 'kismi' => 'Kısmi ödendi', 'odendi' => 'Ödendi', 'iptal' => 'İptal'],
    'plan_statuses' => ['taslak' => 'Taslak', 'onaylandi' => 'Onaylandı', 'islendi' => 'İşlendi', 'iptal' => 'İptal'],
    'recurrences' => ['tek' => 'Tek sefer', 'aylik' => 'Aylık', 'uc_aylik' => 'Üç aylık', 'yillik' => 'Yıllık'],
    'distributions' => ['esit' => 'Eşit', 'm2' => 'm² oranında', 'arsa_payi' => 'Arsa payı oranında', 'sabit' => 'Sabit tutar (birim başına)', 'grup' => 'Aidat grubuna göre', 'manuel' => 'Manuel'],
    'payment_methods' => ['nakit' => 'Nakit', 'havale' => 'Havale', 'eft' => 'EFT', 'cek' => 'Çek', 'mahsup' => 'Mahsup / avans', 'diger' => 'Diğer'],
    'payment_statuses' => ['gecerli' => 'Geçerli', 'iptal' => 'İptal', 'iade' => 'İade'],
    'allocation_modes' => ['eski' => 'En eski borçtan başla', 'manuel' => 'Manuel seç', 'avans' => 'Avansa al'],
    'account_types' => ['kasa' => 'Kasa (nakit)', 'banka' => 'Banka hesabı'],
    'document_kinds' => ['fatura' => 'Fatura', 'fis' => 'Fiş', 'makbuz' => 'Makbuz', 'sozlesme' => 'Sözleşme', 'dekont' => 'Dekont', 'diger' => 'Diğer'],
    'expense_statuses' => ['planlandi' => 'Planlandı', 'kismi' => 'Kısmi ödendi', 'odendi' => 'Ödendi', 'gecikti' => 'Gecikti', 'iptal' => 'İptal'],
    'vat_modes' => ['dahil' => 'KDV dahil', 'haric' => 'KDV hariç', 'yok' => 'KDV yok'],
    'late_fee_rate_types' => ['aylik' => 'Aylık sabit oran', 'gunluk' => 'Günlük oran'],
    'late_fee_start_rules' => ['vade' => 'Vade ertesi gün', 'ay_gunu' => 'Ayın belirli günü'],
    'budget_statuses' => ['taslak' => 'Taslak', 'onayli' => 'Onaylı', 'revizyonda' => 'Revizyonda', 'kapali' => 'Kapalı'],
    'meter_types' => ['su' => 'Su', 'elektrik' => 'Elektrik', 'dogalgaz' => 'Doğalgaz', 'isi' => 'Isı (kalorimetre)', 'sicak_su' => 'Sıcak su'],
    'request_categories' => ['ariza' => 'Arıza', 'temizlik' => 'Temizlik', 'guvenlik' => 'Güvenlik', 'sikayet' => 'Şikayet', 'oneri' => 'Öneri', 'diger' => 'Diğer'],
    'request_priorities' => ['dusuk' => 'Düşük', 'normal' => 'Normal', 'yuksek' => 'Yüksek', 'acil' => 'Acil'],
    'request_statuses' => ['yeni' => 'Yeni', 'inceleniyor' => 'İnceleniyor', 'atandi' => 'Atandı', 'devam' => 'Devam ediyor', 'beklemede' => 'Beklemede', 'tamamlandi' => 'Tamamlandı', 'iptal' => 'İptal'],
    'request_visibilities' => ['ozel' => 'Yalnızca talep sahibi ve yönetim', 'herkes' => 'Tüm sakinler görebilir'],
    'announcement_targets' => ['tumu' => 'Tüm sakinler', 'blok' => 'Belirli blok', 'bolum' => 'Belirli bağımsız bölüm', 'rol' => 'Belirli rol (malik/kiracı)', 'kisi' => 'Belirli kişi'],
    'announcement_channels' => ['uygulama' => 'Uygulama', 'eposta' => 'Uygulama + e-posta', 'sms' => 'Uygulama + SMS'],
    'announcement_priorities' => ['normal' => 'Normal', 'onemli' => 'Önemli', 'acil' => 'Acil'],
    'document_categories' => ['yonetim_plani' => 'Yönetim planı', 'karar_defteri' => 'Karar defteri', 'isletme_projesi' => 'İşletme projesi', 'sozlesme' => 'Sözleşme', 'fatura' => 'Fatura / gider belgesi', 'sigorta' => 'Sigorta poliçesi', 'tutanak' => 'Tutanak', 'denetim' => 'Denetim raporu', 'diger' => 'Diğer'],
    'document_visibilities' => ['yonetim' => 'Yalnızca yönetim', 'sakinler' => 'Tüm sakinler', 'malikler' => 'Yalnızca malikler'],
    'meeting_types' => ['olagan' => 'Olağan genel kurul', 'olaganustu' => 'Olağanüstü genel kurul', 'yonetim' => 'Yönetim kurulu', 'denetim' => 'Denetim toplantısı'],
    'meeting_statuses' => ['planlandi' => 'Planlandı', 'yapildi' => 'Yapıldı', 'ertelendi' => 'Ertelendi', 'iptal' => 'İptal'],
    'staff_positions' => ['kapici' => 'Kapıcı', 'temizlik' => 'Temizlik görevlisi', 'guvenlik' => 'Güvenlik', 'bahcivan' => 'Bahçıvan', 'teknik' => 'Teknik personel', 'yonetici_asistani' => 'Yönetici asistanı', 'diger' => 'Diğer'],
    'asset_statuses' => ['aktif' => 'Aktif', 'arizali' => 'Arızalı', 'bakimda' => 'Bakımda', 'hurda' => 'Hurda / elden çıkarıldı'],
    'contract_statuses' => ['aktif' => 'Aktif', 'sona_erdi' => 'Sona erdi', 'feshedildi' => 'Feshedildi'],
    'notification_channels' => ['uygulama' => 'Uygulama', 'eposta' => 'E-posta', 'sms' => 'SMS'],
    'debt_visibility' => ['gizli' => 'Sakinler borçlu listesini görmez', 'kapi_no' => 'Yalnızca kapı numarası ve tutar', 'isim' => 'Kapı numarası, ad ve tutar'],
    'poll_types' => ['tek' => 'Tek seçim', 'coklu' => 'Çoklu seçim'],
    'period_statuses' => ['acik' => 'Açık', 'kapali' => 'Kapalı'],
    'transfer_kinds' => ['virman' => 'Virman (hesaplar arası)', 'nakit_yatirma' => 'Kasadan bankaya yatırma', 'nakit_cekme' => 'Bankadan kasaya çekme'],
    'expense_categories_default' => [
        ['name' => 'Personel', 'children' => ['Kapıcı maaşı', 'SGK primi', 'Kıdem / ihbar karşılığı', 'Temizlik görevlisi', 'Güvenlik']],
        ['name' => 'Enerji ve su', 'children' => ['Ortak alan elektriği', 'Ortak alan suyu', 'Doğalgaz / yakıt', 'Jeneratör yakıtı']],
        ['name' => 'Bakım ve onarım', 'children' => ['Asansör bakımı', 'Asansör periyodik muayene', 'Hidrofor / su deposu', 'Kazan / kombi bakımı', 'Yangın sistemi', 'Çatı ve dış cephe', 'Elektrik tesisatı', 'Su tesisatı', 'Boya badana', 'Diğer onarım']],
        ['name' => 'Temizlik ve bahçe', 'children' => ['Temizlik malzemesi', 'Bahçe bakımı', 'İlaçlama', 'Çöp / atık']],
        ['name' => 'Sigorta ve hukuk', 'children' => ['Bina sigortası (DASK / yangın)', 'Avukat / icra masrafı', 'Noter', 'Mahkeme harcı']],
        ['name' => 'Yönetim giderleri', 'children' => ['Yönetici ücreti', 'Kırtasiye', 'Banka masrafı', 'Yazılım / abonelik', 'Posta / kargo', 'Muhasebe / mali müşavir']],
        ['name' => 'Demirbaş ve yatırım', 'children' => ['Demirbaş alımı', 'Kamera / güvenlik sistemi', 'Otomat kapı', 'Yenileme projesi']],
        ['name' => 'Diğer', 'children' => ['Diğer gider']],
    ],
    'income_categories_default' => ['Aidat', 'Gecikme tazminatı', 'Demirbaş katkı payı', 'Ortak alan kira geliri', 'Reklam / baz istasyonu geliri', 'Banka faiz geliri', 'Bağış', 'Devir bakiyesi', 'Diğer gelir'],
];
